---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(scales) # install.packages("scales")
```

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)
```

```{r}
annual_esc <- esc %>%
  separate(sampleDate, into = c("Year", "Month", "Day", sep = "-"))

head(annual_esc)
```

```{r}
annual_esc <- esc %>% 
  annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))

head(annual_esc)
```

## ggplot

```{r}
ggplot(annual_esc, mapping = aes(x = Species, y = escapement))+
  geom_col()
```

```{r}
kodiak_esc <- annual_esc %>%
  filter(SASAP.Region == "Kodiak'")
```

```{r}
ggplot(kodiak_esc, aes(x = Year, y = Day))
geom_point()+
  geom_line()+
  ylab("Daily (num fish")+
  ggtitle("Kodiak Daily")+
  theme_bw()
```

## leaflet

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~ Location)
```

